name: Deploy

on:
  push: {}
  pull_request: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm create vite@latest my-vue-app -- --template vue
      - name: Job.
        run: npm run start:dev
        env:
          NODE_ENV: production
